// app/src/app/features/public-rankings/public-rankings.component.ts
import { DatePipe, NgTemplateOutlet } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, effect, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgbNavModule } from '@ng-bootstrap/ng-bootstrap';

import { ApiService } from '../../core/api.service';
import { AuthStore } from '../../core/auth.store';
import { SeasonStore } from '../../core/season.store';
import { LoadingService } from '../../core/loading.service';
import { calculateRankings, calculatePenaltyRankings, RankingEntry } from '../../core/points';
import type { Cup, Driver, Race, RaceResult } from '../../core/models';
import { DriverImageComponent } from '../../shared/kt-driver-image/kt-driver-image.component';
import { EmptyStateComponent } from '../../shared/kt-empty-state/kt-empty-state.component';
import { SkeletonRowComponent } from '../../shared/kt-skeleton-row/kt-skeleton-row.component';
import { LapTimePipe } from '../../shared/pipes/lap-time.pipe';

interface CalendarRow {
  race: Race;
  winner: Driver | null;
  fastestLapDriver: Driver | null;
  fastestLapTime: string | null;
}

/**
 * Public rankings landing page.
 *
 * Tabs (via `ngbNav`):
 *  - Calendar   — chronological race list with winner + fastest lap
 *  - Overall    — championship-wide ranking (only `affects_championship` races)
 *  - <Cup name> — per-cup rankings, one tab each, sorted by `cups.start_date`
 *  - Penalties  — per-driver penalty totals (last tab)
 */
@Component({
  selector: 'kt-public-rankings',
  standalone: true,
  imports: [
    NgbNavModule,
    RouterLink,
    NgTemplateOutlet,
    DatePipe,
    DriverImageComponent,
    EmptyStateComponent,
    SkeletonRowComponent,
    LapTimePipe,
  ],
  templateUrl: './public-rankings.component.html',
  styleUrl: './public-rankings.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PublicRankingsComponent {
  private readonly api = inject(ApiService);
  private readonly loading = inject(LoadingService);
  protected readonly seasonStore = inject(SeasonStore);
  protected readonly auth = inject(AuthStore);

  /** Active tab id: 'calendar' | 'overall' | 'cup:<id>' | 'penalty'. */
  protected readonly activeTab = signal<string>('calendar');

  protected readonly cups = signal<Cup[]>([]);
  protected readonly races = signal<Race[]>([]);
  protected readonly results = signal<RaceResult[]>([]);
  protected readonly error = signal<string | null>(null);
  protected readonly loadingList = signal<boolean>(true);

  /** Seasons surfaced in the season selector — only those `is_ongoing`. */
  protected readonly ongoingSeasons = computed(() =>
    this.seasonStore.seasons().filter((s) => s.is_ongoing),
  );

  /** Cups sorted by `start_date` asc (per the resume plan). */
  protected readonly sortedCups = computed(() =>
    [...this.cups()].sort((a, b) => (a.start_date ?? '').localeCompare(b.start_date ?? '')),
  );

  protected readonly overallRanking = computed<RankingEntry[]>(() => {
    const overallRaces = this.races().filter((r) => r.affects_championship);
    return calculateRankings(overallRaces, this.results(), { type: 'overall' });
  });

  protected readonly penaltyRanking = computed<RankingEntry[]>(() => {
    const overallRaces = this.races().filter((r) => r.affects_championship);
    return calculatePenaltyRankings(overallRaces, this.results(), { type: 'overall' });
  });

  /** Build calendar rows with winner + fastest-lap-driver per race. */
  protected readonly calendarRows = computed<CalendarRow[]>(() => {
    const races = [...this.races()].sort((a, b) =>
      (a.race_datetime ?? '').localeCompare(b.race_datetime ?? ''),
    );
    const resultsByRace = new Map<string, RaceResult[]>();
    for (const r of this.results()) {
      const arr = resultsByRace.get(r.race_id) ?? [];
      arr.push(r);
      resultsByRace.set(r.race_id, arr);
    }
    return races.map((race): CalendarRow => {
      const bucket = resultsByRace.get(race.id) ?? [];
      const winner =
        bucket
          .filter((r) => !r.is_disqualified)
          .sort((a, b) => a.finish_position - b.finish_position)[0]?.drivers ?? null;
      const withLap = bucket.filter((r) => !!r.best_lap_time && !r.is_disqualified);
      withLap.sort((a, b) => (a.best_lap_time ?? '').localeCompare(b.best_lap_time ?? ''));
      const fastest = withLap[0];
      return {
        race,
        winner,
        fastestLapDriver: fastest?.drivers ?? null,
        fastestLapTime: fastest?.best_lap_time ?? null,
      };
    });
  });

  /** Per-cup ranking memoised lazily by tab id. */
  protected cupRanking(cupId: string): RankingEntry[] {
    const cupRaces = this.races().filter((r) => r.cup_id === cupId);
    return calculateRankings(cupRaces, this.results(), { type: 'cup' });
  }

  constructor() {
    effect(() => {
      const seasonId = this.seasonStore.selectedSeasonId();
      if (seasonId) void this.load(seasonId);
    });
  }

  protected onSeasonChange(value: string): void {
    this.seasonStore.select(value || null);
  }

  private async load(seasonId: string): Promise<void> {
    this.error.set(null);
    this.loadingList.set(true);
    try {
      await this.loading.track(
        (async () => {
          const [cups, races] = await Promise.all([
            this.api.listCups(seasonId),
            this.api.listRaces({ seasonId }),
          ]);
          this.cups.set(cups);
          this.races.set(races);
          const raceIds = races.map((r) => r.id);
          const results = await this.api.listRaceResultsByRaceIds(raceIds);
          this.results.set(results);
        })(),
      );
    } catch (e) {
      this.error.set((e as Error).message);
    } finally {
      this.loadingList.set(false);
    }
  }
}

<div class="container mt-4">
  <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3">
    <h1 class="h3 mb-0">
      {{ seasonStore.selectedSeason()?.name ?? '—' }}
    </h1>
    @if (ongoingSeasons().length > 1) {
      <div>
        <label class="form-label me-2 mb-0 small" for="season-sel" i18n>Season</label>
        <select
          id="season-sel"
          class="form-select form-select-sm d-inline-block"
          style="width: auto"
          [value]="seasonStore.selectedSeasonId() ?? ''"
          (change)="onSeasonChange($any($event.target).value)"
        >
          @for (s of ongoingSeasons(); track s.id) {
            <option [value]="s.id">{{ s.name }}</option>
          }
        </select>
      </div>
    }
  </div>

  @if (error()) {
    <div class="alert alert-danger">{{ error() }}</div>
  }

  <ul ngbNav #nav="ngbNav" [(activeId)]="activeTab" class="nav-tabs mb-3">
    <!-- Calendar tab -->
    <li [ngbNavItem]="'calendar'">
      <button ngbNavLink i18n>Calendar</button>
      <ng-template ngbNavContent>
        <div class="table-responsive">
          <table class="table table-striped align-middle">
            <thead>
              <tr>
                <th i18n>Date</th>
                <th i18n>Race</th>
                <th i18n>Location</th>
                <th i18n>Winner</th>
                <th i18n>Fastest lap</th>
              </tr>
            </thead>
            @if (loadingList()) {
              <tbody kt-skeleton-row [columns]="5"></tbody>
            } @else if (calendarRows().length === 0) {
              <tbody>
                <tr>
                  <td colspan="5">
                    <kt-empty-state
                      icon="calendar"
                      title="No races yet"
                      message="Once races are scheduled, they will appear here."
                      i18n-title
                      i18n-message
                    />
                  </td>
                </tr>
              </tbody>
            } @else {
              <tbody>
                @for (row of calendarRows(); track row.race.id) {
                  <tr>
                    <td>{{ row.race.race_datetime | date: 'mediumDate' }}</td>
                    <td>
                      @if (auth.isAdmin()) {
                        <a [routerLink]="['/admin/races', row.race.id]">{{ row.race.name }}</a>
                      } @else {
                        {{ row.race.name }}
                      }
                    </td>
                    <td>{{ row.race.location }}</td>
                    <td>
                      @if (row.winner) {
                        <div class="d-flex align-items-center gap-2">
                          <kt-driver-image [src]="row.winner.picture_url" [name]="row.winner.name" size="sm" />
                          <span>{{ row.winner.name }}</span>
                        </div>
                      } @else {
                        <span class="text-muted">—</span>
                      }
                    </td>
                    <td>
                      @if (row.fastestLapDriver) {
                        <div class="d-flex align-items-center gap-2">
                          <kt-driver-image [src]="row.fastestLapDriver.picture_url" [name]="row.fastestLapDriver.name" size="sm" />
                          <span>{{ row.fastestLapDriver.name }} · <em>{{ row.fastestLapTime | lapTime }}</em></span>
                        </div>
                      } @else {
                        <span class="text-muted">—</span>
                      }
                    </td>
                  </tr>
                }
              </tbody>
            }
          </table>
        </div>
      </ng-template>
    </li>

    <!-- Overall tab -->
    <li [ngbNavItem]="'overall'">
      <button ngbNavLink i18n>Overall</button>
      <ng-template ngbNavContent>
        <ng-container *ngTemplateOutlet="rankingTable; context: { $implicit: overallRanking() }" />
      </ng-template>
    </li>

    <!-- Per-cup tabs -->
    @for (cup of sortedCups(); track cup.id) {
      <li [ngbNavItem]="'cup:' + cup.id">
        <button ngbNavLink>{{ cup.name }}</button>
        <ng-template ngbNavContent>
          <ng-container *ngTemplateOutlet="rankingTable; context: { $implicit: cupRanking(cup.id) }" />
        </ng-template>
      </li>
    }

    <!-- Penalties tab (last) -->
    <li [ngbNavItem]="'penalty'">
      <button ngbNavLink i18n>Penalties</button>
      <ng-template ngbNavContent>
        <ng-container *ngTemplateOutlet="rankingTable; context: { $implicit: penaltyRanking() }" />
      </ng-template>
    </li>
  </ul>

  <div [ngbNavOutlet]="nav"></div>
</div>

<!-- Shared ranking-table template (reused by overall/cup/penalty tabs). -->
<ng-template #rankingTable let-rows>
  <div class="table-responsive">
    <table class="table table-striped align-middle">
      <thead>
        <tr>
          <th>#</th>
          <th i18n>Driver</th>
          <th class="text-end" i18n>Points</th>
          <th class="text-end d-none d-md-table-cell" i18n>Poles</th>
          <th class="text-end d-none d-md-table-cell" i18n>FL</th>
          <th class="text-end" i18n>Pen.</th>
        </tr>
      </thead>
      @if (loadingList()) {
        <tbody kt-skeleton-row [columns]="6"></tbody>
      } @else if (rows.length === 0) {
        <tbody>
          <tr>
            <td colspan="6">
              <kt-empty-state
                icon="trophy"
                title="No results yet"
                message="Once races are imported, the ranking will appear here."
                i18n-title
                i18n-message
              />
            </td>
          </tr>
        </tbody>
      } @else {
        <tbody>
          @for (entry of rows; track entry.driverId) {
            <tr>
              <td class="fw-bold text-primary">{{ entry.rank }}</td>
              <td>
                <div class="d-flex align-items-center gap-2">
                  <kt-driver-image [src]="entry.picture" [name]="entry.name" size="sm" />
                  <span>{{ entry.name }}</span>
                </div>
              </td>
              <td class="text-end fw-semibold">{{ entry.totalPoints }}</td>
              <td class="text-end d-none d-md-table-cell">{{ entry.poles }}</td>
              <td class="text-end d-none d-md-table-cell">{{ entry.fastestLaps }}</td>
              <td class="text-end">{{ entry.penalties }}</td>
            </tr>
          }
        </tbody>
      }
    </table>
  </div>
</ng-template>

// react/src/pages/PublicRankings.jsx
import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { useSeason } from "@/context/SeasonContext";
import { DriverImage } from "@/lib/driverImage";
import { listCups, listRaces, listRaceResultsByRaceIds } from "@/lib/api";
import {
  calculateRankings,
  calculatePenaltyRankings,
  parseLapTime,
} from "@/lib/points";

export function PublicRankings() {
  const { t } = useTranslation();
  const { seasons, selectedSeasonId, setSeasonId } = useSeason();

  const [races, setRaces] = useState([]);
  const [cups, setCups] = useState([]);
  const [raceResults, setRaceResults] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const [selectedSeason, setSelectedSeason] = useState(null);

  useEffect(() => {
    const load = async () => {
      if (!selectedSeasonId) {
        setLoading(false);
        return;
      }

      try {
        setLoading(true);
        setError("");

        const loadedCups = await listCups({
          seasonId: selectedSeasonId,
          order: { column: "start_date", ascending: true },
        });
        setCups(loadedCups);

        const loadedRaces = await listRaces({
          filters: [
            { column: "season_id", operator: "eq", value: selectedSeasonId },
          ],
          order: { column: "race_datetime", ascending: true },
        });
        setRaces(loadedRaces);

        if (loadedRaces.length) {
          const raceIds = loadedRaces.map((r) => r.id);
          const loadedResults = await listRaceResultsByRaceIds(raceIds);
          setRaceResults(loadedResults);
        } else {
          setRaceResults([]);
        }
      } catch (err) {
        console.error("Error loading rankings:", err);
        setError(
          err.message ||
            t("common.errors.routeLoad", { message: "Unknown error" }),
        );
      } finally {
        setLoading(false);
      }
    };

    load();
  }, [selectedSeasonId, t]);

  const raceResultsByRace = new Map();
  raceResults.forEach((r) => {
    if (!raceResultsByRace.has(r.race_id)) raceResultsByRace.set(r.race_id, []);
    raceResultsByRace.get(r.race_id).push(r);
  });

  const now = Date.now();

  const getDriverDisplay = (result) => {
    if (!result) return null;
    const driver = result.drivers || {};
    return {
      name: driver.name || t("common.misc.unknown"),
      picture: driver.picture_url || null,
      seed: result.driver_id || driver.email || driver.name || null,
    };
  };

  const renderDriverCell = (driver) => {
    if (!driver) return "-";
    return (
      <div className="d-flex align-items-center gap-2">
        <DriverImage
          src={driver.picture}
          seed={driver.seed || driver.name}
          alt={driver.name}
          className="rounded-circle"
          size={32}
        />
        <span>{driver.name}</span>
      </div>
    );
  };

  const getWinnerDriver = (results) => {
    if (!results || !results.length) return null;
    const winner = results.find(
      (result) => Number(result.finish_position) === 1,
    );
    return getDriverDisplay(winner);
  };

  const getFastestLapDriver = (results) => {
    if (!results || !results.length) return null;
    let best = null;
    results.forEach((result) => {
      const time = parseLapTime(result.best_lap_time);
      if (time === null) return;
      const finish = Number.isFinite(Number(result.finish_position))
        ? Number(result.finish_position)
        : Number.MAX_SAFE_INTEGER;
      if (
        !best ||
        time < best.time ||
        (time === best.time && finish < best.finish)
      ) {
        best = { result, time, finish };
      }
    });
    return best ? getDriverDisplay(best.result) : null;
  };

  const getRaceTimestamp = (race) => {
    if (!race || !race.race_datetime) return null;
    const time = new Date(race.race_datetime).getTime();
    return Number.isNaN(time) ? null : time;
  };

  const overallRaces = races.filter(
    (race) => race.affects_championship !== false,
  );

  const sections = [
    {
      id: "calendar",
      label: t("publicRankings.calendar"),
      type: "calendar",
      races,
    },
    {
      id: "overall",
      label: t("publicRankings.overallChampionship"),
      races: overallRaces,
      ranking: "points",
    },
    ...cups.map((cup) => ({
      id: `cup-${cup.id}`,
      label: cup.name,
      races: races.filter((race) => race.cup_id === cup.id),
      ranking: "points",
    })),
    {
      id: "penalties",
      label: t("publicRankings.penalties"),
      races: overallRaces,
      ranking: "penalties",
    },
  ];

  const orderedCalendarRaces = [...races].sort((left, right) => {
    const leftTime = getRaceTimestamp(left) ?? Number.MAX_SAFE_INTEGER;
    const rightTime = getRaceTimestamp(right) ?? Number.MAX_SAFE_INTEGER;
    if (leftTime !== rightTime) return leftTime - rightTime;
    return String(left.name || "").localeCompare(String(right.name || ""));
  });

  return (
    <div className="container mt-4">
      <div className="d-flex gap-2 mb-3 align-items-center">
        <div className="h5 mb-0">{t("publicRankings.title")}</div>
        <div className="d-flex w-auto">
          <select
            className="form-select form-select-sm"
            id="season-name"
            aria-label={t("publicRankings.seasonLabel")}
            value={selectedSeasonId || ""}
            onChange={(e) => setSeasonId(e.target.value)}
          >
            {seasons.map((season) => (
              <option key={season.id} value={season.id}>
                {season.name}
              </option>
            ))}
          </select>
        </div>
      </div>

      {error && <div className="alert alert-danger">{error}</div>}

      {loading ? (
        <div className="d-flex align-items-center gap-2">
          <div className="spinner-border spinner-border-sm" role="status"></div>
          <span>{t("common.status.loadingRankings")}</span>
        </div>
      ) : !selectedSeasonId ? (
        <div className="alert alert-info">
          {t("publicRankings.noAvailableSeasonsYet")}
        </div>
      ) : (
        <>
          <ul className="nav nav-tabs" id="rankings-tabs" role="tablist">
            {sections.map((section, index) => (
              <li className="nav-item" role="presentation" key={section.id}>
                <button
                  className={`nav-link ${index === 0 ? "active" : ""} text-nowrap`}
                  data-bs-toggle="tab"
                  data-bs-target={`#${section.id}`}
                  type="button"
                  role="tab"
                  id={`${section.id}-tab`}
                >
                  {section.label}
                </button>
              </li>
            ))}
          </ul>

          <div className="tab-content" id="rankings-content">
            {sections.map((section, index) => {
              if (section.type === "calendar") {
                return (
                  <div
                    className={`tab-pane fade ${index === 0 ? "show active" : ""}`}
                    id={section.id}
                    role="tabpanel"
                    key={section.id}
                  >
                    <div className="table-responsive">
                      <table className="table table-striped align-middle">
                        <thead>
                          <tr>
                            <th>{t("publicRankings.table.raceDate")}</th>
                            <th>{t("publicRankings.table.raceName")}</th>
                            <th>{t("publicRankings.table.winner")}</th>
                            <th>{t("publicRankings.table.fastestLap")}</th>
                          </tr>
                        </thead>
                        <tbody>
                          {orderedCalendarRaces.map((race) => {
                            const raceTime = getRaceTimestamp(race);
                            const isCompleted =
                              raceTime !== null && raceTime <= now;
                            const results =
                              raceResultsByRace.get(race.id) || [];
                            const showResults = isCompleted && results.length;
                            const winner = showResults
                              ? getWinnerDriver(results)
                              : null;
                            const fastest = showResults
                              ? getFastestLapDriver(results)
                              : null;

                            return (
                              <tr key={race.id}>
                                <td>
                                  {race.race_datetime
                                    ? new Date(
                                        race.race_datetime,
                                      ).toLocaleString()
                                    : "-"}
                                </td>
                                <td>
                                  {race.id ? (
                                    <Link
                                      className="fw-semibold text-decoration-underline"
                                      to={`/admin/race?id=${race.id}`}
                                    >
                                      {race.name || "-"}
                                    </Link>
                                  ) : (
                                    race.name || "-"
                                  )}
                                  <small>{race.location || "-"}</small>
                                </td>
                                <td>{renderDriverCell(winner)}</td>
                                <td>{renderDriverCell(fastest)}</td>
                              </tr>
                            );
                          })}
                        </tbody>
                      </table>
                    </div>
                  </div>
                );
              }

              const sectionResults = raceResults.filter((result) =>
                section.races.some((race) => race.id === result.race_id),
              );

              const rankings =
                section.ranking === "penalties"
                  ? calculatePenaltyRankings(section.races, sectionResults, {
                      type: "overall",
                    })
                  : calculateRankings(section.races, sectionResults, {
                      type: section.id === "overall" ? "overall" : "cup",
                    });

              if (!section.races.length || !sectionResults.length) {
                return (
                  <div
                    className={`tab-pane fade ${index === 0 ? "show active" : ""}`}
                    id={section.id}
                    role="tabpanel"
                    key={section.id}
                  >
                    <div className="alert alert-info">
                      {t("publicRankings.noResultsTab")}
                    </div>
                  </div>
                );
              }

              return (
                <div
                  className={`tab-pane fade ${index === 0 ? "show active" : ""}`}
                  id={section.id}
                  role="tabpanel"
                  key={section.id}
                >
                  <div className="table-responsive">
                    <table className="table table-striped align-middle">
                      <thead>
                        <tr>
                          <th>{t("publicRankings.table.position")}</th>
                          <th>{t("publicRankings.table.driver")}</th>
                          <th>{t("publicRankings.table.totalPoints")}</th>
                          <th>{t("publicRankings.table.penalties")}</th>
                          <th>{t("publicRankings.table.bestPosition")}</th>
                        </tr>
                      </thead>
                      <tbody>
                        {rankings.map((driver, i) => (
                          <tr key={driver.driverId}>
                            <td>{i + 1}</td>
                            <td>
                              <div className="d-flex align-items-center gap-2">
                                <DriverImage
                                  src={driver.picture}
                                  seed={driver.driverId || driver.name}
                                  alt={driver.name}
                                  className="rounded-circle"
                                  size={36}
                                />
                                <span>{driver.name}</span>
                              </div>
                            </td>
                            <td className="fw-semibold">
                              {driver.totalPoints}
                            </td>
                            <td>{driver.penalties || 0}</td>
                            <td>{driver.bestPosition || "-"}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              );
            })}
          </div>
        </>
      )}
    </div>
  );
}
